### ISSUE TITLE
Sistem Arayüzleri

### ISSUE THREAD

**Issue by huseyinocal** [huseyinocal/BBM487-20142-2#12]
Akademisyen, öğrenci işleri personeli ve öğrenci için arayüzler tasarlanmalı ve sistem tasarımı tamamlanmalıdır.

**Comment by EnsarKoseoglu** [comment]
Sistem kullanıcıları için (akademisyen, öğrenci ve öğrenci işleri personeli) arayüzler tasarlandı ve sistem tasarımı yapılarak kodlamaya hazır hale getirildi.
